INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Restaurants', 'restaurants', 0, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Afghan', 'afghani', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('African', 'african', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Senegalese', 'senegalese', 3, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('South African', 'southafrican', 3, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('American (New)', 'newamerican', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('American (Traditional)', 'tradamerican', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Arabian', 'arabian', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Argentine', 'argentine', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Armenian', 'armenian', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Asian Fusion', 'asianfusion', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Australian', 'australian', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Austrian', 'austrian', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Bangladeshi', 'bangladeshi', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Barbeque', 'bbq', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Basque', 'basque', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Belgian', 'belgian', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Brasseries', 'brasseries', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Brazilian', 'brazilian', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Breakfast & Brunch', 'breakfast_brunch', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('British', 'british', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Buffets', 'buffets', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Burgers', 'burgers', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Burmese', 'burmese', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Cafes', 'cafes', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Cafeteria', 'cafeteria', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Cajun/Creole', 'cajun', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Cambodian', 'cambodian', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Caribbean', 'caribbean', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Dominican', 'dominican', 29, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Haitian', 'haitian', 29, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Puerto Rican', 'puertorican', 29, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Trinidadian', 'trinidadian', 29, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Catalan', 'catalan', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Chech', 'chech', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Cheesesteaks', 'cheesesteaks', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Chicken Shop', 'chickenshop', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Chicken Wings', 'chicken_wings', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Chinese', 'chinese', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Cantonese', 'cantonese', 39, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Dim Sum', 'dimsum', 39, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Shanghainese', 'shanghainese', 39, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Szechuan', 'szechuan', 39, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Comfort Food', 'comfortfood', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Creperies', 'creperies', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Cuban', 'cuban', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Czech', 'czech', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Delis', 'delis', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Diners', 'diners', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Ethiopian', 'ethiopian', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Fast Food', 'hotdogs', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Filipino', 'filipino', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Fish & Chips', 'fishnchips', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Fondue', 'fondue', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Food Court', 'food_court', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Food Stands', 'foodstands', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('French', 'french', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Gastropubs', 'gastropubs', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('German', 'german', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Gluten-Free', 'gluten_free', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Greek', 'greek', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Halal', 'halal', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Hawaiian', 'hawaiian', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Himalayan/Nepalese', 'himalayan', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Hot Dogs', 'hotdog', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Hot Pot', 'hotpot', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Hungarian', 'hungarian', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Iberian', 'iberian', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Indian', 'indpak', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Indonesian', 'indonesian', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Irish', 'irish', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Italian', 'italian', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Japanese', 'japanese', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Ramen', 'ramen', 73, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Teppanyaki', 'teppanyaki', 73, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Korean', 'korean', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Kosher', 'kosher', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Laotian', 'laotian', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Latin American', 'latin', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Colombian', 'colombian', 79, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Salvadoran', 'salvadoran', 79, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Venezuelan', 'venezuelan', 79, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Live/Raw Food', 'raw_food', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Malaysian', 'malaysian', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Mediterranean', 'mediterranean', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Falafel', 'falafel', 85, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Mexican', 'mexican', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Middle Eastern', 'mideastern', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Egyptian', 'egyptian', 88, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Lebanese', 'lebanese', 88, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Modern European', 'modern_european', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Mongolian', 'mongolian', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Moroccan', 'moroccan', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Pakistani', 'pakistani', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Persian/Iranian', 'persian', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Peruvian', 'peruvian', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Pizza', 'pizza', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Polish', 'polish', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Portuguese', 'portuguese', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Poutineries', 'poutineries', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Russian', 'russian', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Salad', 'salad', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Sandwiches', 'sandwiches', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Scandinavian', 'scandinavian', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Scottish', 'scottish', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Seafood', 'seafood', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Singaporean', 'singaporean', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Slovakian', 'slovakian', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Soul Food', 'soulfood', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Soup', 'soup', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Southern', 'southern', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Spanish', 'spanish', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Sri Lankan', 'srilankan', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Steakhouses', 'steak', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Sushi Bars', 'sushi', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Taiwanese', 'taiwanese', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Tapas Bars', 'tapas', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Tapas/Small Plates', 'tapasmallplates', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Tex-Mex', 'tex-mex', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Thai', 'thai', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Turkish', 'turkish', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Ukrainian', 'ukrainian', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Uzbek', 'uzbek', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Vegan', 'vegan', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Vegetarian', 'vegetarian', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Vietnamese', 'vietnamese', 1, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Nightlife', 'nightlife', 0, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Adult Entertainment', 'adultentertainment', 127, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Bars', 'bars', 127, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Airport Lounges', 'airportlounges', 129, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Champagne Bars', 'champagne_bars', 129, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Cocktail Bars', 'cocktailbars', 129, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Dive Bars', 'divebars', 129, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Gay Bars', 'gaybars', 129, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Hookah Bars', 'hookah_bars', 129, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Irish Pub', 'irish_pubs', 129, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Lounges', 'lounges', 129, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Pubs', 'pubs', 129, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Sports Bars', 'sportsbars', 129, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Wine Bars', 'wine_bars', 129, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Beer Gardens', 'beergardens', 127, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Comedy Clubs', 'comedyclubs', 127, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Country Dance Halls', 'countrydancehalls', 127, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Dance Clubs', 'danceclubs', 127, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Jazz & Blues', 'jazzandblues', 127, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Karaoke', 'karaoke', 127, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Music Venues', 'musicvenues', 127, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Piano Bars', 'pianobars', 127, now(), now());
INSERT INTO yelp.categories (display, api, parent, createdAt, updatedAt) VALUES ('Pool Halls', 'poolhalls', 127, now(), now());